version: '3.5'

services:
  ministra_db:
    container_name: ministra_db
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=stalker_db
      - MYSQL_USER=stalker
      - MYSQL_PASSWORD=QRcTrYaxujYewd35
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./src/db/delta:/tmp/mysql/delta
      - ./conf/mysql:/etc/mysql/mysql.conf.d

  ministra_php:
    container_name: ministra_php
    depends_on:
      - ministra_db
    build:
      context: ./src
      dockerfile: ./build/Dockerfile
      args:
        buildno: 1
    volumes:
      - ./src:/var/www/html/stalker_portal
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/apache2/ports.conf:/etc/apache2/ports.conf

  ministra_nginx:
    container_name: ministra_nginx
    image: nginx:latest
    depends_on:
      - ministra_php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./conf/nginx:/etc/nginx/conf.d
